# Generated by Django 3.1.5 on 2021-01-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_product', '0002_auto_20210109_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
