# Generated by Django 3.1.5 on 2021-01-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
