# Generated by Django 2.2 on 2021-01-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='bc_item_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
