# Generated by Django 2.2 on 2021-01-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='user_id',
        ),
    ]
