# Generated by Django 3.1.5 on 2021-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carts',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
