# Generated by Django 3.1.5 on 2021-01-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210109_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='user_id',
            new_name='user_id_id',
        ),
    ]
