# Generated by Django 3.1.5 on 2021-01-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210110_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='user_id_id',
            new_name='user_id',
        ),
    ]
