# Generated by Django 3.1.5 on 2021-01-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart_id',
        ),
    ]
