# Generated by Django 3.1.5 on 2021-01-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
