# Generated by Django 2.2 on 2021-01-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sku', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=5000)),
                ('date_created', models.CharField(default='', max_length=200)),
                ('date_modified', models.CharField(default='', max_length=200)),
                ('option_set_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='variant_id')),
                ('bc_product_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
