# Generated by Django 2.2 on 2021-01-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210114_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='option_set_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='variant_id'),
        ),
    ]
